### ISSUE TITLE
[Bug] Player option 'dialog' shows dialog with no results instead of falling back to select a player. 

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#117]
The current behaviour of the 'dialog' option in a player doesn't take into account empty results. In. my opinion, it shouldn't show the empty dialog altogether so a different player could be selected to try to find a match for the video selected.

**Comment by jurialmunkey** [comment]
I think this commit should fix the issue: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/c64e5c5ab890eb3a3903065ebfaeb70dd3dad06b

Can you test and confirm?

**Comment by juanma-cvega** [comment]
I just tested it with the latest version but it doesn't do anything now, not even showing the dialog saying 'None' as no results are found. I enabled debug logging but I didn't see anything there. These are the logs. https://pastebin.com/KaHev7Rj

**Comment by jurialmunkey** [comment]
Okay, hopefully this commit will fix the issue: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/eb38e18bb4b2f63529301ae98c76ea258aa2b209

Can you test latest and see if it is working correctly for you now?

**Comment by juanma-cvega** [comment]
Ok, now it seems to work but I have a question. For what I understand from your first answer, by cancelling the dialog it's expected to have the list of players as another dialog to select from. But that happens even when there are results returned. In my opinion, if the user cancels the dialog it should be his choice whether he wants to try another player by selecting 'Play using' from the context menu or not. And when there are no results, isn't there any way to directly show the list of available players instead of having to first cancel the empty one?

**Comment by juanma-cvega** [comment]
I just realised, the one I tested before is still not showing anything after calling the player (EmbyCon player in this case). Is there any way to know whether the problem is with the player or if there is something else going on? The logs are the same I pasted before, there is not much to work with there.

**Comment by jurialmunkey** [comment]
> 
> 
> Ok, now it seems to work but I have a question. For what I understand from your first answer, by cancelling the dialog it's expected to have the list of players as another dialog to select from. But that happens even when there are results returned. In my opinion, if the user cancels the dialog it should be his choice whether he wants to try another player by selecting 'Play using' from the context menu or not. And when there are no results, isn't there any way to directly show the list of available players instead of having to first cancel the empty one?

Good point. This commit should make the necessary changes: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/2e57e629c8c575450e97d77a1a901ac0a7d9bc6a

If the dialog is empty, it shouldn't even be shown. Is an empty dialog being shown?
(Can you also test with latest?)

**Comment by juanma-cvega** [comment]
> If the dialog is empty, it shouldn't even be shown. Is an empty dialog being shown?
Can you get me a screenshot of the empty dialog if that's the case?

This is a screenshot of the dialog. https://pasteboard.co/IXrAUi6.png . I assumed that's the result of an empty list returned by the player as there aren't any episodes of the TV show I selected in the Emby server. Normally you would see a label with the name of the video from the Emby server. And selecting the 'None' option just closes the dialog.  

> What do you mean by "still not showing anything" ?

Basically that it does nothing. The spinning wheel appears a couple of seconds and then it just disappears and nothing happens. Only that with your latest changes it seems like it kind of works now because I can see the dialog but with 'None' as a result. 
I don't know if you reverted something with your last commits because now it's back at the starting point. For a single result it shows again the dialog box instead of just playing it, for no results it shows the same dialog as in the screenshot and cancelling the dialog doesn't bring forward the dialog to select a different player.

**Comment by jurialmunkey** [comment]
> Basically that it does nothing. The spinning wheel appears a couple of seconds and then it just disappears and nothing happens. Only that with your latest changes it seems like it kind of works now because I can see the dialog but with 'None' as a result.

I mean in what scenario does this occur? Are you saying that when you select an item from the dialog it does nothing? When does it do/display nothing? What are the steps taken and what is expected to happen? It's not clear what you are saying is not working...

**Comment by jurialmunkey** [comment]
> This is a screenshot of the dialog. https://pasteboard.co/IXrAUi6.png . I assumed that's the result of an empty list returned by the player as there aren't any episodes of the TV show I selected in the Emby server. Normally you would see a label with the name of the video from the Emby server. And selecting the 'None' option just closes the dialog.

Okay, that screen shot is helpful. I think what is happening is that when there are no results, a None type object is returned so to TMDbHelper it appears that there is still at least one item.

Can you test latest. I think I've got it working now

----

Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/8bab3a31290ca8a817c2e8977e84982a51c72192

**Comment by juanma-cvega** [comment]
Yesterday I didn't have time to test. Hopefully I'll do it today.

**Comment by juanma-cvega** [comment]
Awesome! Now it works.

**Comment by jurialmunkey** [comment]
Excellent! We got there in the end 😉
