### ISSUE TITLE
[BUG] Director sometimes is missing

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1504]
### Describe the bug

A little strange situation is happening. For some movies, I don't get a director at all. Why, I haven't found out yet. At first I thought it was my skin but then I noticed the same thing with AF2. Let's say I enter the video info dialog of the movie:
The Accountant 2
there is no director.
Death of Unicron
there is a director.
Havoc 
there is no director...
I know, it's vague and silly, but I've tried everything and the same thing keeps happening.
If you can check if it happens to you and what should I try. What can it be? I've never had such problems before, and I didn't change anything in the skin code.

### Steps To Reproduce

-

### Debug log

-

### Screenshots and Additional Info

-

### Checklist

- [x] I have searched the issues and this bug has not been reported.
- [x] I have updated TMDbHelper to the most recent version.
- [x] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Lookups of cast and crew are only done as part of lists with detailed=TRUE as otherwise it is slow to write thousands of cast and crew members to the database.

The service does a detailed lookup. Previously cached details for standard infolabels (like director and cast) are added to a list even if detailed=false on the list itself. If it was previously cached I the service you will get crew details. 

Cacheonly=false without detailed only does a simple lookup for basic details and artwork, not an extended lookup of cast and crew.

**Comment by matke-84** [comment]
Ok. I understood that the service monitor must be used even if I am not a fan of it where basic Kodi's info labels can be used, only for the reason that on weak devices such as android boxes the information is delayed for a few seconds. I would much prefer if there was a way to limit the number of cast and crew when it comes to item details in the lists, so that it does not search for hundreds of actors per movies and shows. And who should use it use the list, for example, `plugin://plugin.video.themoviedb.helper?info=stars_in_tvshows&amp;type=person&amp;tmdb_id=1100`. Of course, all under the assumption that it is possible and that tmdb api allows it. But it doesn't matter now, you decided on this way and I respect that.
In any case, the service monitor does not work properly here either. It just doesn't find the director for some movies, which is interesting, although I see in your AF2 skin that it didn't even find a picture of the screenwriter.
These are screenshots of your AF2, TMDb Helper 6.8.6:
![Image](https://github.com/user-attachments/assets/5a5749a4-a29d-466f-aaa8-7840f29d5535)
TMDb Helper 6.0.10
![Image](https://github.com/user-attachments/assets/b2b8336c-6e4f-4c5d-83e1-f414c1a63675)

**Comment by jurialmunkey** [comment]
>  In any case, the service monitor does not work properly here either.

I believe this is a case of one person having two separate crew roles credited to them. In which case, that is addressed by this change: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/f1765cfe7aa6130f3ffb67315a504a15612e9ef3

**Comment by OfficerKD637** [comment]
~~I'm not sure if this is a related issue but I think that director,writer,creator, etc. properties aren't working with the Container(99950) method anymore since the last couple versions.
$INFO[Container(99950).ListItem.Property(Director.1.Name)] or Director.1.Thumb doesn't work but I can get Container(99950).ListItem.Director/Writer to work as a fallback.~~

~~AF2 with the Window(Home) properties does show the director name/thumbs though. AFAIK AF1 and 2 use almost exactly the same paths to fetch info from TMDbH and the only real differentiator is the Container vs Window method (and I haven't changed any of that)~~

~~If this is a separate issue, I can open a fresh bug report.~~

EDIT: All working now except cast in TV Shows/Seasons/Episodes.

**Comment by matke-84** [comment]
I think the problem is solved but now I'm getting some error.
```
2025-05-20 11:45:33.683 T:81404    info <general>: [plugin.video.themoviedb.helper]
                                                   lib.monitor.listitem.on_listitem
                                                   Error Type: AttributeError
                                                   Error Contents: ("'ListItemMonitorFinaliserContainerMethod' object has no attribute 'processed_artwork'",)
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\script.module.jurialmunkey\resources\modules\jurialmunkey\logger.py", line 66, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\tmdbhelper\lib\monitor\listitemtools.py", line 393, in on_listitem
                                                       self.on_finalise()
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\tmdbhelper\lib\monitor\listitemtools.py", line 367, in on_finalise
                                                       func(self).finalise()
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\tmdbhelper\lib\monitor\listitemtools.py", line 223, in finalise
                                                       self.start_process_default()
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\tmdbhelper\lib\monitor\listitemtools.py", line 238, in start_process_default
                                                       self.listitem.setArt(self.processed_artwork)

```

**Comment by matke-84** [comment]
~~There are no more creator now. I just noticed.~~ And some clearlogos are missing. Actually, I have a creator now, but I don't have the cast for tv shows.

**Comment by matke-84** [comment]
6.8.7 version is still not good. Cast in tv shows are missing. Creator is just late, it remains from the previous show... even in af2 it doesn't work in tv shows in dialog info, ondown to open extended info, because there are no actors.

**Comment by jurialmunkey** [comment]
This is all very vague. Please provide clear steps to reproduce.

**Comment by matke-84** [comment]
Same as with director. I go into dialog info, I don't get cast. Creator very often remains from the previous show, also in dialog info. Just enter your af2 in the dialog info and you will see that you will not be able to open extended info for shows by clicking down.

**Comment by jurialmunkey** [comment]
Still extremely vague. Give me specific lists, specific items.

If it were that obvious then I would see the issue myself and fix it. Saying "you'll see" isn't helpful. 

Cast works correctly for me. Director works correctly for me.

**Comment by jurialmunkey** [comment]
![Image](https://github.com/user-attachments/assets/b4668e85-682c-4c0b-981a-999ae56c869e)
![Image](https://github.com/user-attachments/assets/c0868fb4-8a26-4d17-8bc5-20c9e1b6781f)

**Comment by OfficerKD637** [comment]
Using the 'Trending Today' list from TMDbH TV Shows

AF2 - Can't scroll down to access cast (only for TV Shows/Seasons/Episodes)

![Image](https://github.com/user-attachments/assets/1e12be98-f512-4893-825b-40470dde24a5)

AF Mod - Cast empty (only for TV Shows/Seasons/Episodes)

![Image](https://github.com/user-attachments/assets/1f807d98-89bb-46ff-bdf4-b1d428d2a636)

**Comment by matke-84** [comment]
@OfficerKD637 Thanks for this.
@jurialmunkey Try something that is not cached. Direcror is sorted, I just gave an example because that's why I opened this issue.

**Comment by jurialmunkey** [comment]
@OfficerKD637 - Thanks. This was very helpful for me to be able to reproduce the issue.

**Comment by OfficerKD637** [comment]
EDIT: I think I got it haha. Container(99950).ListItem.Property(TVShow.TMDb_ID) is returning empty for episodes and seasons.

Really sorry for commenting on a closed issue but I am noticing a weird bug that I can't seem to resolve. 

The online cast and videos/trailers is returning empty for episodes and seasons (works for TV shows though) on AF Mod.

But everything seems to work fine on AF2. Which leads me to believe maybe there's something I need to update/change in my skin mod?

I looked through my code to see if I am doing anything differently, but everything seems identical apart from using the Container vs Window method.

AF2 path variables:

TRAILERS:
```
<variable name="Path_VideoInfo_Trailers">
        <value condition="String.IsEqual(ListItem.DBType,musicvideo)">$VAR[Path_Youtube_Query,plugin://plugin.video.youtube/kodion/search/query/?q=,&amp;search_type=notvalid]</value>
        <value>$VAR[Path_VideoInfo_Generic,,&amp;info=videos]</value>
    </variable>

    <variable name="Path_VideoInfo_Generic">
        <value condition="!String.IsEmpty(Window(Home).Property(TMDbHelper.ListItem.TMDb_ID)) + String.IsEqual(Window(Home).Property(TMDbHelper.ListItem.base_dbtype),movie)">$INFO[Window(Home).Property(TMDbHelper.ListItem.TMDb_ID),plugin://plugin.video.themoviedb.helper?tmdb_id=,&amp;tmdb_type=movie]</value>
        <value condition="!String.IsEmpty(Window(Home).Property(TMDbHelper.ListItem.TMDb_ID)) + String.IsEqual(Window(Home).Property(TMDbHelper.ListItem.base_dbtype),tvshow)">$INFO[Window(Home).Property(TMDbHelper.ListItem.TMDb_ID),plugin://plugin.video.themoviedb.helper?tmdb_id=,&amp;tmdb_type=tv]</value>
        <value condition="!String.IsEmpty(Window(Home).Property(TMDbHelper.ListItem.TVShow.TMDb_ID)) + String.IsEqual(Window(Home).Property(TMDbHelper.ListItem.base_dbtype),season)">$INFO[Window(Home).Property(TMDbHelper.ListItem.TVShow.TMDb_ID),plugin://plugin.video.themoviedb.helper?tmdb_id=,&amp;tmdb_type=tv]$INFO[Window(Home).Property(TMDbHelper.ListItem.Season),&amp;season=,]</value>
        <value condition="!String.IsEmpty(Window(Home).Property(TMDbHelper.ListItem.TVShow.TMDb_ID)) + String.IsEqual(Window(Home).Property(TMDbHelper.ListItem.base_dbtype),episode)">$INFO[Window(Home).Property(TMDbHelper.ListItem.TVShow.TMDb_ID),plugin://plugin.video.themoviedb.helper?tmdb_id=,&amp;tmdb_type=tv]$INFO[Window(Home).Property(TMDbHelper.ListItem.Season),&amp;season=,]$INFO[Window(Home).Property(TMDbHelper.ListItem.Episode),&amp;episode=,]</value>
        <value>-</value>
    </variable>
```

ONLINE CAST:
`$VAR[Path_VideoInfo_Generic,,&amp;info=cast&amp;aggregate=true]$VAR[Path_Param_Widget]`

AF Mod

TRAILERS:
```
<variable name="Path_VideoInfo_Trailers">
        <value condition="String.IsEqual(ListItem.DBType,musicvideo)">$VAR[Path_Youtube_Query,plugin://plugin.video.youtube/kodion/search/query/?q=,&amp;search_type=notvalid]</value>
        <value>$VAR[Path_VideoInfo_Generic,,&amp;info=videos]</value>
    </variable>

    <variable name="Path_VideoInfo_Generic">
        <value condition="!String.IsEmpty(Container(99950).ListItem.Property(TMDb_ID)) + String.IsEqual(Container(99950).ListItem.DBType,movie)">$INFO[Container(99950).ListItem.Property(TMDb_ID),plugin://plugin.video.themoviedb.helper?tmdb_id=,&amp;tmdb_type=movie]</value>
        <value condition="!String.IsEmpty(Container(99950).ListItem.Property(TMDb_ID)) + String.IsEqual(Container(99950).ListItem.DBType,tvshow)">$INFO[Container(99950).ListItem.Property(TMDb_ID),plugin://plugin.video.themoviedb.helper?tmdb_id=,&amp;tmdb_type=tv]</value>
        <value condition="!String.IsEmpty(Container(99950).ListItem.Property(TVShow.TMDb_ID)) + String.IsEqual(Container(99950).ListItem.DBType,season)">$INFO[Container(99950).ListItem.Property(TVShow.TMDb_ID),plugin://plugin.video.themoviedb.helper?tmdb_id=,&amp;tmdb_type=tv]$INFO[Container(99950).ListItem.Season,&amp;season=,]</value>
        <value condition="!String.IsEmpty(Container(99950).ListItem.Property(TVShow.TMDb_ID)) + String.IsEqual(Container(99950).ListItem.DBType,episode)">$INFO[Container(99950).ListItem.Property(TVShow.TMDb_ID),plugin://plugin.video.themoviedb.helper?tmdb_id=,&amp;tmdb_type=tv]$INFO[Container(99950).ListItem.Season,&amp;season=,]$INFO[Container(99950).ListItem.Episode,&amp;episode=,]</value>
        <value>-</value>
    </variable>
```

ONLINE CAST:
`$VAR[Path_VideoInfo_Generic,,&amp;info=cast&amp;aggregate=true]$VAR[Path_Param_Widget]`

And the Path_Param_Widget variable is identical for both skins `&amp;nextpage=false&amp;fanarttv=false&amp;cacheonly=true&amp;length=1`

I have tried using base_dbtype instead of DBType but it didn't make a difference.

Would greatly appreciate any help.

Thank you!

**Comment by jurialmunkey** [comment]
@OfficerKD637 - You're probably looking for `UniqueId(tvshow.tmdb)` not `Property(tvshow.tmdb_id)`

These were only ever duplicated onto properties of the listitem so that the service would add them as properties to the window, but I don't need to do that anymore. Now I simply convert all unique ids into properties with `_id` suffix without the manual handling.

e.g. 
`UniqueId(tmdb)` becomes `TMDbHelper.ListItem.tmdb_id`
`UniqueId(tvshow.tmdb)` becomes `TMDbHelper.ListItem.tvshow.tmdb_id`
`UniqueId(wikidata)` becomes `TMDbHelper.ListItem.wikidata_id`
`UniqueId(facebook)` becomes `TMDbHelper.ListItem.facebook_id`
etc.

There might be a few lingering places where `Property(tmdb_id)` works, but uniqueid should be the more consistent option.

Also FYI differentiating tvshow.tmdb and tmdb shouldn't be necessary anymore (they *should* always be the same now - but I'm not 100% about Trakt lists with episodes so I don't want to assert that 100% yet!)

**Comment by OfficerKD637** [comment]
You're literally the GOAT. I've been wracking my brain for hours and you gave me the solution in seconds haha.

https://github.com/user-attachments/assets/4868e265-7603-4e42-b04e-620b0489e6cf

**Comment by OfficerKD637** [comment]
@jurialmunkey Apologies in advance for commenting on a closed issue but I wasn't sure if this was a bug or maybe something that's intended.

AF1/Mod uses `ListItem.Icon` to fetch the cast images in the info dialog but now they have been returning the fallback default blue TMDbH image.

![Image](https://github.com/user-attachments/assets/9c569ad3-049a-4300-8b5f-e78dc9ef4af5)

I can replace it with `ListItem.Art(poster)` to get it working again but wanted to confirm if it maybe was a bug? If it is I can open a separate bug report (with all the necessary info and log of course) and if it's intended I can apply the fix to my skin instead.

Thank you!

**Comment by jurialmunkey** [comment]
@OfficerKD637 - Yeah sorry, I got it back-to-front. It should have icon/thumb but *not* poster (since these are people and dont have posters...)

EDIT: FYI this should fix it https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/ad725e68b22013a7df1c04cafeaf82db24b5e8a3

**Comment by OfficerKD637** [comment]
That was insanely fast! Thank you so much! 
Some of us might have not noticed but I think you're able to fix bugs much faster after the code refactor! (provided we supply all important info and logs haha). 

We all really appreciate you for everything that you do for the community!
