### ISSUE TITLE
The MovieDb Helper 'Non-type' object is not callable

### ISSUE THREAD

**Issue by cannabarman** [jurialmunkey/plugin.video.themoviedb.helper#380]
Hi,
I've got the following error at each menu view change.
It seems to be like ZedeN1 few days ago, (issues #376 , #301, #288 , #244 ), but I'm not using Manjaro, I'm using Raspbian and downgrading numpy as mentioned in issue #244 module is not working here.

Hardware : Raspberry Pi 4
Kodi 18.7
The MovieDb Helper 4.0.65
Artic Horizon 0.5.52

Anyone knows how to correct it ?

The entire log [here](https://pastebin.com/ah2TyY3N)
The error in particular : 

```php
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 4, in <module>
                                                from resources.lib.script.router import Script
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 25, in <module>
                                                from resources.lib.monitor.images import ImageFunctions
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/monitor/images.py", line 10, in <module>
                                                from PIL import ImageFilter, Image  # TODO: Try Import in-case no PIL and don't use funcs
                                              File "/usr/lib/python2.7/dist-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/home/pi/.local/lib/python2.7/site-packages/numpy/__init__.py", line 162, in <module>
                                                from . import ma
                                              File "/home/pi/.local/lib/python2.7/site-packages/numpy/ma/__init__.py", line 44, in <module>
                                                from . import core
                                              File "/home/pi/.local/lib/python2.7/site-packages/numpy/ma/core.py", line 1240, in <module>
                                                add = _MaskedBinaryOperation(umath.add)
                                              File "/home/pi/.local/lib/python2.7/site-packages/numpy/ma/core.py", line 1003, in __init__
                                                super(_MaskedBinaryOperation, self).__init__(mbfunc)
                                              File "/home/pi/.local/lib/python2.7/site-packages/numpy/ma/core.py", line 895, in __init__
                                                self.__doc__ = ufunc.__doc__
                                              File "/home/pi/.local/lib/python2.7/site-packages/numpy/core/_internal.py", line 726, in _ufunc_doc_signature_formatter
                                                in_args = ', '.join('x{}'.format(i+1) for i in range(ufunc.nin))
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--
```

**Comment by jurialmunkey** [comment]
It's not something I can really fix from my side because it is an issue where the modules in the distribution are overriding Kodi's inbuilt python modules. It's basically a matter of getting finding the right versions of the PIL and numpy modules that work together correctly.

I've pushed a patch to master that will at least suppress the errors. That way you can still use TMDbHelper without constant exceptions. The only impact it will have is that you won't be able to use the image functions like Blur. So for Arctic Horizon you will need to use either the Overlay or Vignette background style instead. Everything else should work as normal, however.

**Comment by cannabarman** [comment]
Thank you, I will test it as soon as possible !

Have a great weekend.

**Comment by jurialmunkey** [comment]
@cannabarman - Wondering if you've had a chance to test yet?

**Comment by cannabarman** [comment]
@jurialmunkey - Just did it this morning (log [here](https://pastebin.com/v30yrJMK)), there is still an error, but it changed : 

> ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 4, in <module>
                                                from resources.lib.script.router import Script
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 25, in <module>
                                                from resources.lib.monitor.images import ImageFunctions
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/monitor/images.py", line 10, in <module>
                                                from PIL import ImageFilter, Image  # TODO: Try Import in-case no PIL and don't use funcs
                                              File "/usr/lib/python2.7/dist-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/multiarray.py", line 12, in <module>
                                                from . import overrides
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--

**Comment by jurialmunkey** [comment]
Fixed in matrix
