### ISSUE TITLE
Imported TV shows from Trakt no added to the playlist

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#386]
I just tried with a couple of series, each one added to a different Trakt list and I could verify they are not added to the a playlist with the name of the Trakt list as it used to do. Another thing that I'm not sure it was that way but, once a TV show is added to a list, didn't it use to be added automatically to the library if the list was in the watching list? Currently I have to either add it manually to the library or wait/trigger the Trakt lists synchronisation.

**Comment by jurialmunkey** [comment]
> I just tried with a couple of series, each one added to a different Trakt list and I could verify they are not added to the a playlist with the name of the Trakt list as it used to do.

How are you adding these lists? Are they from the watched lists or manually via context menu?

> Another thing that I'm not sure it was that way but, once a TV show is added to a list, didn't it use to be added automatically to the library if the list was in the watching list? Currently I have to either add it manually to the library or wait/trigger the Trakt lists synchronisation.

No, you always had to wait for the update to happen or trigger it manually after adding something to a watched list on Trakt. For that to work I'd need to be constantly calling Trakt to find out if there were changes.

If you mean adding an item to list via TMDbHelper context menu, I can't remember if it used to work like that or not but it is definitely possible to do (basically would just check if the list name is in the watched lists and prompt user to also add to library).

**Comment by jurialmunkey** [comment]
@juanma-cvega - Can you test latest for a fix to the playlist generation issue. I'm assuming the issue was that shows that were complete skipped from the update (due to having been previously added and not currently airing) weren't returning a playlist rule.

**Comment by juanma-cvega** [comment]
I'll test once I get the time to play with it again. 
Just to clarify, I meant adding them to Trakt through the context menu. 
I noticed two things when playing with it, maybe your recent changes fix this? If you add a TV show to Trakt through the context menu, it ends up in the list alright but then, for it to show up in your library, you have to either add it manually again through the context menu or wait/trigger the synchronisation. The problem with adding the show manually is that, for what I saw from the test, it doesn't add the TV show to the corresponding playlist, so maybe at that point the code is not checking whether it belongs to a Trakt list. 
Another weird behaviour I saw this morning is that most of the TV shows I had in the playlist suddenly disappeared. It remained only 3 and some time later when I rechecked there were only 2 available. I'm not sure what triggered that behaviour but rerunning the synchronisation fixed the issue.

**Comment by jurialmunkey** [comment]
@juanma-cvega - Wondering if you got a chance to test the playlist fix yet?

Also, can you test latest version that I just pushed? Should now prompt also to add to library when adding to a monitored user list.

**Comment by juanma-cvega** [comment]
Sorry, I completely forgot. I haven't had the time lately to watch anything.
I just installed master on a MacBook I use for testing and I'm getting an exception when updating the library. That Kodi instance is only used for testing so it could be something with my setup. I reauthorised Trakt just in case but the error persists. 
```
2020-12-05 10:51:43.505  NOTICE: [plugin.video.themoviedb.helper]
                                            UPDATING TV SHOWS LIBRARY
2020-12-05 10:51:43.506  ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/script.py", line 7, in <module>
                                                Script().router()
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 358, in router
                                                return self.routing_table[route_taken](**self.params)
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 331, in <lambda>
                                                'library_autoupdate': lambda **kwargs: library_update(**kwargs),
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 266, in library_update
                                                force=kwargs.get('force', False))
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/userlist.py", line 63, in library_autoupdate
                                                user_lists = get_monitor_userlists(list_slugs, user_slugs)
                                              File "/Users/juan/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/userlist.py", line 15, in get_monitor_userlists
                                                return [(i, saved_users[x]) for x, i in enumerate(saved_lists)]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-12-05 10:52:50.274 T:123145572413440 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
```

**Comment by jurialmunkey** [comment]
I think you might need to re-add your monitor lists. Looks like you've got a pre v4 setting

**Comment by juanma-cvega** [comment]
I had to manually edit the settings.xml file to get rid of the monitored lists for it to work but I'm finally able to test.
I admit I'm a bit confused now with the context menu. I went to the list of popular TV shows to add a random series to a Trakt list and I realised the TMDBHelper Options doesn't contain any Trakt option, only Manage Artwork. I guess I did the same thing before but I didn't realise about this. I added the show through the Trakt Options at the root of the context menu. Is that the right way to do it? If that's the case it didn't work, the show was added to the list but that's it. 
As a side note, by doing this on a MacBook I realised the difference in speed when adding to the library. I know the code is already make use of threads but I was wondering if there could be any missing feature that could be added to improve performance in Android boxes. I'm using an Nvidia Shield 2019 pro and the difference in performance is night and day.

**Comment by jurialmunkey** [comment]
>  I went to the list of popular TV shows to add a random series to a Trakt list and I realised the TMDBHelper Options doesn't contain any Trakt option, only Manage Artwork.

That subfolder is provided by the context menu addon and is only for external items. Internal items have all their options displayed at the base level of the menu by default.

External context menu shouldn't be showing for internal items at all. As a side note, I've just added an extra check to the context menu addon so that it shouldn't show for internal items.


> I added the show through the Trakt Options at the root of the context menu. Is that the right way to do it? If that's the case it didn't work, the show was added to the list but that's it.

Yes that's the correct way.

Did you re-add the list to the monitored lists in settings first? It will only ask you if the list you're adding to is one of the monitored lists. Also, make sure that you are definitely attempting to add to the same list that is in the monitored lists.

All that happens when you add the item to the list is that the script checks if the list ID matches an ID saved in the monitored lists. If it matches it asks you if you want to add the item. It has to work (assuming monitor list is setup correctly and you definitely are adding to the same list) because if the ID is different then it isn't the same list and thus wouldn't update at the scheduled time either (because you'd get the wrong list).

**Comment by juanma-cvega** [comment]
Ok, just tested again and you were right, I forgot to readd the lists to the monitor one after fixing my problem. Now when I add an element, it asks me whether I want to add it to the library as well. But the show is still no added to the playlist though. I also verified the element is my Trakt list and in the library. 
Another question, would it be possible to add a "Remove from list" option to Trakt? I know the addon doesn't physically delete files but it would allow me to tidy my lists up from the addon and would also work with my setup where I use playlists for the widgets (given this new option would remove elements from playlists once removed from the Trakt list).

**Comment by jurialmunkey** [comment]
Remove from list should already be in Trakt options context menu. You need to be inside the list you want to remove the item from and you need to own the list.

**Comment by juanma-cvega** [comment]
> Remove from list should already be in Trakt options context menu. You need to be inside the list you want to remove the item from and you need to own the list.

Ok, my bad. I just checked and it's as you said.

**Comment by audiosistem** [comment]
Hello, man! In v.4.10.23, there is the possibility to mark manually seen, if trakt doesn't do it. In the later ones, it doesn't work for me anymore. Can you look, when you have time? Thank you, in advance! You do an exceptional job!

**Comment by jurialmunkey** [comment]
> Hello, man! In v.4.10.23, there is the possibility to mark manually seen, if trakt doesn't do it. In the later ones, it doesn't work for me anymore. Can you look, when you have time? Thank you, in advance! You do an exceptional job!

@audiosistem - Please don't piggy back on other issue threads with off-topic issues. If you have an issue then you need to open a new issue report. You're looking for context menu addon https://github.com/jurialmunkey/context.themoviedb.helper/releases
