### ISSUE TITLE
The MovieDB Helper trakt error

### ISSUE THREAD

**Issue by ElGuyARc** [jurialmunkey/plugin.video.themoviedb.helper#454]
Good Morning,

I'm having an issue where I'm not getting my trakt information on Kodi 19 lasted build.
I have done a clean install and same issue.

ERROR <general>: Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\api\mapping.py:54: SyntaxWarning: "is not" with a literal. Did you mean "!="?
                                                     if not pv and pv is not 0:
                                                   
2021-03-09 12:15:05.621 T:7672    ERROR <general>: Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\api\mapping.py:88: SyntaxWarning: "is not" with a literal. Did you mean "!="?

ERROR <general>: XFILE::CFile::Delete - Error deleting file Roaming\Kodi\userdata\addon_data\plugin.video.themoviedb.helper\database\TMDb.db
2021-03-09 12:16:15.494 T:17500    INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.addon.cache get_cache
                                                   Error Type: FileExistsError
                                                   Error Contents: (17, 'Cannot create a file when that file already exists')
                                                     Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\addon\decorators.py", line 11, in wrapper
                                                       return func(*args, **kwargs)
                                                     File Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\addon\cache.py", line 21, in get_cache
                                                       self._cache = self._cache or SimpleCache(filename=self._filename, mem_only=self._mem_only)
                                                     File "Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\addon\simplecache.py", line 41, in __init__
                                                       self._db_file = get_file_path(folder, filename)
                                                     File "Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\files\utils.py", line 85, in get_file_path
                                                       return os.path.join(get_write_path(folder, join_addon_data), filename)
                                                     File "Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\files\utils.py", line 102, in get_write_path
                                                       os.makedirs(main_dir)
                                                     File "C:\Program Files\Kodi\system\python\Lib\os.py", line 223, in makedirs
                                                       mkdir(name, mode)
                                                     if not v and v is not 0:

**Comment by jurialmunkey** [comment]
Full log please. You can upload by dragging and dropping the log file into a comment.

**Comment by ElGuyARc** [comment]
don't know what was the issue but I close and reopen Kodi 3 time and the 3rd time trakt worked. It's crazy cause I spend the whole day yesterday troubleshooting it. I don't have the old logs I deleted them. if the issue happens again I will make sure to upload the logs.

**Comment by ElGuyARc** [comment]
I broke it again when I installed a addon
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6112535/kodi.log)

**Comment by jurialmunkey** [comment]
That's a different error.

Looks like a misconfigured player file.

What addon are you attempting to play with? Please post the player file being used.

**Comment by ElGuyARc** [comment]
[plugin.video.venom.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6112570/plugin.video.venom.zip)

**Comment by ElGuyARc** [comment]
[players.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6112582/players.zip)

thanks

**Comment by jurialmunkey** [comment]
Yep misconfigured player files. TMDbH does not provide a `{rating}` key.

Available keys are listed in the wiki:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#available-keys

You will need to speak to the provider of the players as these are third party and so aren't maintained by me.

@drinfernoo - One for you.

**Comment by ElGuyARc** [comment]
thank you for your help

**Comment by ElGuyARc** [comment]
thanks.. i just test it and its working

**Comment by ElGuyARc** [comment]
it worked with &amp;meta=%7B%22rating%22%3A+%22{rating}

**Comment by 123Venom** [comment]
@jurialmunkey I'm just curious if there was a functionality change made to TMDBHelper for Kodi Matrix that effected this?  That `rating ` key has honestly been there for ages and most likely the result of a port over from OpenMeta players. It was fine before.  I'm removing the key to fix the issue however so this is just a curiosity question cause I'm scratching my head how it all of a sudden stopped working.

**Comment by 123Venom** [comment]
I have a small issue going on while I was trying to look into this issue.  I've not fully setup TMDBHelper yet so I first went to install a player set from [tmdbplayers](http://bit.ly/tmdbplayers) and immediately threw this log error
```
2021-03-10 23:56:30.241 T:15216   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: write() argument must be str, not bytes
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Ken Brown\Desktop\Kodi - Shield\portable_data\addons\plugin.video.themoviedb.helper\script.py", line 10, in <module>
                                                       TMDbScript.router()
                                                     File "C:\Users\Ken Brown\Desktop\Kodi - Shield\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\script.py", line 464, in router
                                                       self.update_players()
                                                     File "C:\Users\Ken Brown\Desktop\Kodi - Shield\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\script.py", line 347, in update_players
                                                       downloader.get_extracted_zip()
                                                     File "C:\Users\Ken Brown\Desktop\Kodi - Shield\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\downloader.py", line 128, in get_extracted_zip
                                                       target.write(_file.read())
                                                   TypeError: write() argument must be str, not bytes
                                                   -->End of Python script error report<--

**Comment by jurialmunkey** [comment]
> I'm just curious if there was a functionality change made to TMDBHelper for Kodi Matrix that effected this? That rating key has honestly been there for ages and most likely the result of a port over from OpenMeta players.

There haven't been any significant changes to player handling in months. It is likely due to change in the way that Python 3 handles string formatting - probably is stricter in raising exceptions for missing keys. I imagine the issue has always been there but is only now being reported due to Matrix becoming the main Kodi release.

The rating key has never been available in TMDbH - just before the string formatter probably returned None whereas now the Py3 string formatter raises an exception due to the missing key instead.

> I have a small issue going on while I was trying to look into this issue. I've not fully setup TMDBHelper yet so I first went to install a player set from tmdbplayers and immediately threw this log error

What version of TMDbH are you using? I thought I already fixed this issue quite a while ago.

**Comment by 123Venom** [comment]
Makes perfect sense on what now  triggered the key error on that **{rating}**.  Funny thing though when I went in to clean that up...I did previously remove the **{rating}** only parts for **play_episodes** it only still existed for **play_movie**.  I don't know how I gaffed that doing one and not the other...oh well its fixed for both in the 2 player files now..lol

I was on the official Kodi repo version.  I updated to 4.3 from here instead now and the issues I was seeing were all gone.

Also does your player installer from url do any service check for changes/updates?  Could something like that be added so when some  schmuck updates his player files other users would auto get it...notice the little self dig..lol

**Comment by jurialmunkey** [comment]
Currently the players update is manual from settings dialog. I was hesitant to add something which redownloads on a regular basis because often there are no changes at all, so it is just a waste of bandwidth.

Thinking about it now, I should be able to record some type of modified timestamp of md5 hash and only redownload if it no longer matches. I'll have a bit of a think about what the best method might be.

**Comment by ElGuyARc** [comment]
![image](https://user-images.githubusercontent.com/36449592/111393070-4f5e7300-868e-11eb-8f28-4ecbcffad721.png)

when i click on your in progress is not working again.
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6152786/kodi.log)

**Comment by jurialmunkey** [comment]
Your Trakt account is not authenticated. You need to authenticate it in TMDbHelper settings.

**Comment by ElGuyARc** [comment]
Yeah I'm login .. when I go to configuration click on account I connected to my Trakt. Then when I go to progress nothing happens

**Comment by 123Venom** [comment]
> Thinking about it now, I should be able to record some type of modified timestamp of md5 hash and only redownload if it no longer matches. I'll have a bit of a think about what the best method might be.

How about just a simple startup notification?

**Comment by jurialmunkey** [comment]
> 
> 
> Yeah I'm login .. when I go to configuration click on account I connected to my Trakt. Then when I go to progress nothing happens

Well you're definitely not authorised because otherwise the log will say:
```
[plugin.video.themoviedb.helper]
Trakt user account authorized
```

Possibly your Settings.xml file is corrupt. Exit Kodi and delete `Settings.xml` from `kodi/userdata/addon_data/plugin.video.themoviedb.helper/`

Restart Kodi and re-authorise Trakt (you will also need to re-enter your other settings in TMDbH).

**Comment by ElGuyARc** [comment]
The old cause it worked the next day. So I been doing a lot of testing. I been playing with an old skin. What I'm seeing is. No matter what I do. If I try to sync my trakt and it doesn't work. I close kodi wait a bit and try to sync it again with TMDV it works. Next time I will try to delete the setting.xml

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by 123Venom** [comment]
@jurialmunkey unrelated question but in desperation I figured I'd ask a skinner who might know the answer.  I have a very strange issue that takes place in Matrix, but not Leia.  A user asked me for an option to disable player artwork, guess he doesn't like clearart, clearlogo, or discart during playback.  So I gave that to him and all was good till Matrix.  For some odd reason in 19 even though I'm NOT passing these 3 pcs of artwork with `.setArt()` and even use `meta.pop()` when I pass meta to InfoLables to be sure the artwork is not passed there either yet we're still getting clearart and clearlogo during playback in 19.  I've checked a couple skins and it's the same so something is getting this artwork for the player in 19 that doesn't happen in 18...I'm just totally stumped what that could be.  Any idea where this artwork might be coming from in 19?

**Comment by jurialmunkey** [comment]
@123Venom - does the item have a DBID? I was troubleshooting an artwork issue in TMDbH recently and found that in Matrix if the item has a dbid then Kodi will fill the artwork from the library regardless of what you set via python.

**Comment by 123Venom** [comment]
Sorry to have wasted you time on this @jurialmunkey.  I scratched my head till I discovered he's using AutoPlay.  While in this mode it uses `xbmcplugin.setResolvedUrl`.  That method pulls the listItem from the SELECTED episode itemt and not what xbmc.Player() method assigns in the player module.  It did however make me realize to satisfy his needs under an Autoplay setup I need to remove artwork at the episode level, which I never considered to satisfy that desire.
