### ISSUE TITLE
[BUG] TMDBHelper first-run cache initialization error

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#495]
During development of AuraMOD skin, we have found a bug with TMDBHelper that is affecting the functionality of the skin.

Simple log file: https://paste.kodi.tv/vuhesaqiqi.kodi
Debug log file: https://paste.kodi.tv/hasedilojo.kodi

The steps to reproduce this bug are as follows:

1. Remove all library sources
2. Uninstall TMDBHelper, pressing `Yes` to remove all addon data when prompted
3. Install TMDBHelper
4. Open TMDBHelper
5. View error

Quote from the [AuraMOD issue](https://github.com/SerpentDrago/skin.auramod/issues/92#issuecomment-841796944):

> It seems that when installing TMDBHelper on a clean install and running it for the first time, there is a database caching issue. TMDBHelper uses a database, MyVideos119.db, to store actor lookups so they load faster the next time. 
> 
> However due to the error interrupting the first-run cascade, the database becomes corrupted and caching of items does not occur properly. 
> 
> The widgets on the second page are cached beforehand while the initial actor screen is loading and are looked up using the cache after the initial actor screen finishes loading, rather than a direct lookup, which is why it won't allow you to move to the next page.
> 
> The database corruption was identified because transferring MyVideos119.db from a copy of Kodi that is not affected by this bug, into a bugged copy of Kodi, the bug was fixed.
> 
> The database can be easily fixed, without needing to use a working database, using the following steps:
> 
> 1. Go to any TMDBHelper item and use the context menu option `Add to Library`.
> 2. Go to Settings > Media settings > General > Enable `Show hidden files and directories`.
> 3. Go to Settings > Media settings > Library > Videos > `Add videos`.
> 4. Click `Browse` and navigate to the following path: `Kodi folder (it might be called .kodi on Android) > userdata > addon_data > plugin.video.themoviedb.helper > movies / tvshows folder (depends on the item you added in Step 1)` > Press `OK`.
> 5. Change `This directory contains` to movies / tvshows (depends on the item you added in Step 1) then Press `OK`.
> 6. Press `Yes` to refresh information for all items in the path.
> 7. The custom actor window down press should now be working.

The above workaround fixes this bug permanently. Feel free to correct my understanding of this issue, it took a while to narrow down the exact cause as we have not been working from clean Kodi installs during development (we already had some library items added previously for testing purposes).

Does TMDBHelper depend on the Kodi database in some way?

**Comment by inb4after** [comment]
After further testing, we have some corrections:

- TMDBHelper does not store lookups in `MyVideos119.db`
- `MyVideos119.db` is not corrupted as a result of TMDBHelper
- The TMDBHelper error is not likely to be related to this bug
- The AuraMOD bug happens with an empty `MyVideos119.db`

In AuraMOD, the TMDBHelper actor extended info uses the built-in TMDBHelper context menu items as sources for the widget content. These context menu items work regardless of whether the Kodi database is empty.

Is this because TMDBHelper skips checking Kodi database first with the context menu option, but with the widget content, the lookup is checked if it already exists Kodi database first, before checking TMDB?

**Comment by jurialmunkey** [comment]
This issue is related to threading. If two threads of TMDbhelper try to make the cache file at the same time then one will fail because the file already exists.

Once the cache file exists it doesn't try to make a new one anymore (it just edits the original), so after a restart of kodi you won't have this error anymore.

The issue with threads is because they happen concurrently there is a race condition to create the file - both see it doesn't exist so both try to make a new one but one beats the other in actually writing it on disk because disk operations are linear.

The best solution would be for the cache to be created on install but I'm not aware of anything in kodi which triggers a post install routine.II do have a couple of other ideas for solutions -I'll get back to you soon on this.

**Comment by jurialmunkey** [comment]
Latest github version should fix this issue for Matrix. Can you test and confirm?

**Comment by inb4after** [comment]
> 
> 
> Latest github version should fix this issue for Matrix. Can you test and confirm?

Confirmed on a clean install, the database creation error no longer occurs. I don't think it affected any functionality before the update as you mentioned in your explanation, just a QOL improvement when the user first installs the addon. Thanks for the quick fix.

However the bug with the empty Kodi database still occurs which, as suspected, is a separate issue. I'll open a new one so we can investigate this.
